dist: xenial
language: python
script:
  - 'make $TEST'
install:
  - pip3 install -q pipenv
  - make install
  - bash docker-compile.sh
matrix:
  fast_finish: true
  allow_failures:
    - env: TEST='test'
      python: 'nightly'
  include:
    - env: TEST='lint'
      python: '3.6'
    - env: TEST='coverage'
      python: '3.6'
    - env: TEST='test'
      python: '3.7'
    - env: TEST='test'
      python: 'nightly'
# after_success: coveralls
