# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, github-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install libglib2.0-0 libglib2.0-dev
        python -m pip install --upgrade pip
        python -m pip install -q pipenv
        make install
    - name: Build
      run: |
        make build
    - name: Lint code
      continue-on-error: true
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
